---
- name: Set the correct timezone
  file:
    src: "/usr/share/zoneinfo/{{ntp_timezone}}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Install NTP Ubuntu
  apt: name=ntp state=installed

- name: Ensure NTP is running and is enabled at system start 
  service:
    name: "ntp"
    state: started
    enabled: yes
